#!/bin/bash
source /init/shared
# VARIABLES
export INSTALL_DIR='/home/steam/steamcmd/data'
export STEAMCMD_PATH='/home/steam/steamcmd'
export STATE_FILE="/home/steam/config/state"
export SERVER_IP=$(dig TXT +short o-o.myaddr.l.google.com @ns1.google.com | tr -d '\"')
# MAIN
echo "###################################################"
echo "##### Starting PEON SteamCMD server v$VERSION"
echo "##### $(date)"
echo "##### PUBLIC IP [$SERVER_IP]"
echo "###################################################"
# PRE-FLIGHT CHECKS
if [ ! -d /actions ]
then
    state_nok "BAD CONFIG" " [x] Missing '/actions' directory. Please check your config and try again."
    exit 1
fi
# CHECK IF FIRST RUN - (THIS IS THE ONLY TIME SU IS AVAILABLE)
if [ ! -e /init/.initialized ]
then
    echo " [i] FIRST CONTAINER RUN"
    su -c 'chmod -R u+x /init'
    su -c 'chmod -R u+x /actions && chown -R 1000:1000 /actions'
    su -c '/init/00_firstrun' && state_ok "FIRST RUN" || state_nok "FIRST RUN"
    if [ -e /actions/init_custom ]
    then
        echo -n " [i] CUSTOM INIT"
        su -c '/actions/init_custom' && state_ok "CUSTOM INIT" || state_nok "CUSTOM INIT"
    fi
    su -c 'mv /etc/shadow.bkp /etc/shadow'
    touch /init/.initialized 
fi
# Check if the server data directory is empty, or an update has been requested.
if [ -z "$(ls -A /home/steam/steamcmd/data)" ] || [ ! -e "/actions/.update" ]
then
    echo " [i] INSTALL/UPDATE SERVER FILES"
    # INITIALIZE STEAM CLIENT
    echo " [*] UPDATE STEAM CLIENT"
    /init/01_steam && state_ok "INIT STEAM CLIENT" || state_nok "INIT STEAM CLIENT"
    # INITIALIZE GAME SERVER
    echo " [*] UPDATE GAME SERVER"
    /init/02_game_server && state_ok "INIT GAME SERVER" || state_nok "INIT GAME SERVER"
    touch "/actions/.update"
fi
# START GAME SERVER
echo $SERVER_IP > "/home/steam/config/ip"
if [ -e "/actions/server_start" ]
then
    echo " [*] STARTING [$STEAM_ID] GAME SERVER "
    echo -n "STARTED" > $STATE_FILE
    /actions/server_start
else
    state_nok "SERVER START" " [x] ERROR /actions/server_start not found. Did you forget to configure the mount for it?"
fi
# SHUTDOWN SCRIPTS
echo -n "OFFLINE" > $STATE_FILE