#!/bin/bash
source /init/shared
# VARIABLES
export INSTALL_DIR='/home/steam/steamcmd/data'
export STEAMCMD_PATH='/home/steam/steamcmd'
export STATE_FILE="/home/steam/config/state"
export SERVER_IP=$(dig TXT +short o-o.myaddr.l.google.com @ns1.google.com | tr -d '\"')
# MAIN
echo "###################################################"
echo "##### Starting PEON SteamCMD server v$VERSION"
echo "##### $(date)"
echo "##### PUBLIC IP [$SERVER_IP]"
echo "###################################################"
# CHECK IF FIRST RUN - (THIS IS THE ONLY TIME SU IS AVAILABLE)
if [ ! -e /init/.intiliazed ] 
then
    echo " [i] FIRST CONTAINER RUN"
    su -c 'chmod -R u+x /init'
    su -c '/init/00_firstrun' && state_ok "FIRST RUN" || state_nok "FIRST RUN"
    if [ -e /init/init_custom ]
    then
        echo -n " [i] CUSTOM INIT"
        su -c '/init/init_custom' && state_ok "CUSTOM INIT" || state_nok "CUSTOM INIT"
    fi
    su -c 'mv /etc/shadow.bkp /etc/shadow'
    touch /init/.intiliazed 
fi
# Check if the server data directory is empty, or an update has been requested.
if [ -z "$(ls -A /home/steam/steamcmd/data)" ] || [ -e "/home/steam/config/update" ]
then
    echo " [i] INSTALL/UPDATE SERVER FILES"
    # INITIALIZE STEAM CLIENT
    echo " [*] STEAM CLIENT"
    /init/01_steam && state_ok "INIT STEAM CLIENT" || state_nok "INIT STEAM CLIENT"
    # INITIALIZE GAME SERVER
    echo " [*] GAME SERVER"
    /init/02_game_server && state_ok "INIT GAME SERVER" || state_nok "INIT GAME SERVER"
    rm -rf "/home/steam/config/update"
fi
# START GAME SERVER
if [ -e "/init/server_start" ]
then
    echo " [*] STARTING [$STEAMID] GAME SERVER "
    echo -n "ACTIVATED" > $STATE_FILE
    /init/server_start
else
    state_nok "SERVER START"
    echo " [X] ERROR /init/server_start not found. Did you forget to configure the mount for it?"
fi
# SHUTDOWN SCRIPTS
echo -n "OFFLINE" > $STATE_FILE