#!/bin/bash
state_ok(){
    echo " $1 [COMPLETE]"
    echo -n $1 > $STATE_FILE
}

state_nok(){
    echo " $1 [ERROR]"
    if [ -n "$2" ]; then
        echo "$2"
    fi
    echo -n "ERROR" > $STATE_FILE
    touch /init/.firstrun
    exit 1
}
